/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___CHIMARA_MARSHAL_MARSHAL_H__
#define ___CHIMARA_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:UINT,STRING,UINT (chimara/libchimara/chimara-marshallers.txt:3) */
extern
void _chimara_marshal_VOID__UINT_STRING_UINT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:UINT,STRING,STRING (chimara/libchimara/chimara-marshallers.txt:4) */
extern
void _chimara_marshal_VOID__UINT_STRING_STRING (GClosure     *closure,
                                                GValue       *return_value,
                                                guint         n_param_values,
                                                const GValue *param_values,
                                                gpointer      invocation_hint,
                                                gpointer      marshal_data);

/* VOID:STRING,STRING (chimara/libchimara/chimara-marshallers.txt:5) */
extern
void _chimara_marshal_VOID__STRING_STRING (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:BOOLEAN (chimara/libchimara/chimara-marshallers.txt:6) */
#define _chimara_marshal_VOID__BOOLEAN	g_cclosure_marshal_VOID__BOOLEAN


G_END_DECLS

#endif /* ___CHIMARA_MARSHAL_MARSHAL_H__ */
